name: "CI"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "pnpm"

      - run: pnpm install

      - run: pnpm test
      - run: pnpm lint
