name: "Deploy"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libkrb5-dev libxss1 dbus libgtk-3-0 libgbm1
      - run: yarn global add node-gyp
      - run: yarn install

      - run: yarn build

      - run: yarn prepare-deploy

      - uses: ngduc/vercel-deploy-action@master
        with:
          vercel-cli: vercel
          vercel-project-id: prj_WQFxgyAPkR43Ym3Pl1AyOdVzXDQw
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: packages/vscode-host/dist
          vercel-args: "--prod"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
