name: "Deploy"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libkrb5-dev libxss1 dbus libgtk-3-0 libgbm1
      - run: yarn global add node-gyp
      - run: pnpm install

      - name: Build
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            export DETH_IFRAME_URL="https://code.deth.net"
          else
            export DETH_IFRAME_URL="https://dethcode.vercel.app"
          fi

          yarn build

      - run: pnpm prepare-deploy

      - uses: ngduc/vercel-deploy-action@master
        with:
          vercel-cli: vercel
          vercel-project-id: prj_WQFxgyAPkR43Ym3Pl1AyOdVzXDQw
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: packages/vscode-host/dist
          vercel-args: "--prod"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - uses: ngduc/vercel-deploy-action@master
        with:
          vercel-cli: vercel
          vercel-project-id: prj_HUIafaXOjvJCjiz3Ne5kJupck5oN
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: packages/entrypoint/dist
          vercel-args: "--prod"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
