name: "Deploy"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: npm install -g vercel
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libkrb5-dev libxss1 dbus libgtk-3-0 libgbm1
      - run: yarn global add node-gyp
      - run: pnpm install

      - name: Build
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            export DETH_IFRAME_URL="https://code.deth.net"
          else
            export DETH_IFRAME_URL="https://dethcode.vercel.app"
          fi

          yarn build

      - run: pnpm prepare-deploy

      - name: Deploy host to Vercel
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }} # creates vercel output directory

          cp -R ./node_modules ./.vercel/output/static/ # force add node_modules to output directory

          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: packages/vscode-host/dist
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_HOST_PREVIEW_HOST_PROJECT_ID }}

      - name: Deploy entrypoint to Vercel
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }} # creates vercel output directory
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: packages/entrypoint/dist
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID:
            ${{ secrets.VERCEL_ENTRYPOINT_PREVIEW_HOST_PROJECT_ID }}
